import calender
import wakf_registration
import wakf_immovable_property
import wakf_movable_property
import wakf_location
import wakf_management
import wakf_types
import sws_registration
import sws_criteria
import sws_scholar_criteria
import scholar_sanction_criteria
